import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/shared/nav/navbar"
import '@fortawesome/fontawesome-svg-core/styles.css'
import { config } from '@fortawesome/fontawesome-svg-core'
import WorkoutContextProvider from "./context/workoutContext";
import Footer from "./components/shared/footer/footer";
import { ToastContainer } from "react-toastify";
config.autoAddCss = false
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
         <WorkoutContextProvider>
             <Navbar/>
             {children}
             <Footer/>
              <ToastContainer />
         </WorkoutContextProvider>
        </body>
    </html>
  );
}
